(()=>{
 function create({getId,getPosition,canUse,toast,scene,THREE,makeAvatar,disposeAvatar,getVehicle=()=>null}){
  const style=document.createElement('style');style.textContent=`.mission-toggle{position:fixed;right:18px;top:204px;z-index:35;min-width:100px;min-height:44px;border:1px solid #d4ff0060;border-radius:12px;background:#09140eee;color:#d4ff00;font:800 11px system-ui}.mission-card{position:fixed;z-index:40;left:12px;top:160px;width:240px;max-width:calc(100vw - 24px);padding:12px;border:1px solid #d4ff0060;border-radius:14px;background:#09140ef2;color:#eff5e8;font:12px system-ui}.mission-card[hidden],.mission-toggle[hidden]{display:none!important}.mission-card header{display:flex;justify-content:space-between;gap:8px;align-items:center}.mission-card button{min-height:44px;min-width:44px;border:1px solid #d4ff0050;border-radius:9px;background:#213626;color:#e4ff93;font:800 11px system-ui;touch-action:manipulation}.mission-card p{line-height:1.5;margin:8px 0}.mission-card footer{display:flex;gap:6px}.mission-card footer button{flex:1}.mission-distance{display:block;margin:8px 0;color:#d4ff00}.mission-card button:disabled{opacity:.5}.photo-mode .mission-card,.photo-mode .mission-toggle,.mobile-avatar-preview .mission-card,.mobile-avatar-preview .mission-toggle{display:none!important}@media(max-width:760px),(pointer:coarse){.mission-toggle{top:112px;right:calc(108px + env(safe-area-inset-right));min-width:80px}.mission-card{top:164px;left:12px;width:220px}}@media(orientation:landscape) and (pointer:coarse){.mission-toggle{top:58px;right:calc(244px + env(safe-area-inset-right));min-width:80px}.mission-card{top:108px;left:140px;width:240px;max-height:calc(100dvh - 120px);overflow:auto}}`;document.head.append(style);
  style.textContent+=' .mission-card{box-sizing:border-box;max-height:calc(100dvh - 180px);overflow:auto}';
  const toggle=document.createElement('button');toggle.type='button';toggle.className='mission-toggle';toggle.textContent='ENTREGAS';toggle.hidden=true;document.body.append(toggle);
  const card=document.createElement('section');card.className='mission-card';card.hidden=true;card.setAttribute('aria-label','Missão de entrega');card.innerHTML='<header><strong>ENTREGAS LOWKEY</strong><button type="button" aria-label="Fechar missões">×</button></header><p></p><span class="mission-distance"></span><footer><button type="button"></button><button type="button">CANCELAR</button></footer>';document.body.append(card);
  const mode=document.createElement('select'),route=document.createElement('select');mode.setAttribute('aria-label','Tipo de atividade');mode.innerHTML='<option value="delivery">TRABALHO LEGAL · ENTREGAS</option><option value="illicit">CLANDESTINO · FAVELA</option><option value="race">CORRIDAS</option>';route.setAttribute('aria-label','Circuito da corrida');route.hidden=true;for(const e of [mode,route]){e.style.cssText='width:100%;min-height:44px;margin-top:6px;border-radius:8px;background:#213626;color:#eff5e8;border:1px solid #d4ff0050';card.querySelector('header').after(e);}let routesFilled=false,lastCheckpointRequest=0;
  card.querySelector('strong').textContent='TRABALHOS LOWKEY';
  const description=card.querySelector('p'),distance=card.querySelector('span'),[action,cancel]=card.querySelectorAll('footer button');let revision=0,model=null,modelAt=0,busy=false,lastId=null,lastPoll=0,inFlight=false,lastFrame=0;
  const ring=new THREE.Mesh(new THREE.TorusGeometry(1.5,.12,6,24),new THREE.MeshBasicMaterial({color:0xd4ff00}));ring.rotation.x=-Math.PI/2;ring.visible=false;scene.add(ring);
  let contactsId=null;const contacts=[];
  function syncContacts(){const a=model?.active?.kind==='race'?null:model?.active,id=a?.id||(!model?.active&&mode.value==='illicit'&&model?.broker?'broker':null);if(contactsId===id)return;for(const rig of contacts){scene.remove(rig.group);disposeAvatar(rig.group);}contacts.length=0;contactsId=id;if(!id||!makeAvatar)return;
   for(const [role,p] of a?[['RETIRADA',a.pickup],['ENTREGA',a.destination]]:[['CONTATO',model.broker]]){const contact=p.contact||{name:role,appearance:{skin:'#ad7958',hair:'#201b19',hairStyle:'fade',shirt:'#426c91',pants:'#263348',shoe:'#e5e4dc'}},rig=makeAvatar(contact.appearance,contact.name);rig.group.position.set(p.x,p.y,p.z);const other=a?(role==='RETIRADA'?a.destination:a.pickup):{x:p.x,z:p.z+1};rig.group.rotation.y=Math.atan2(other.x-p.x,other.z-p.z);
    const canvas=document.createElement('canvas');canvas.width=256;canvas.height=64;const ctx=canvas.getContext('2d');ctx.fillStyle='#09140ee6';ctx.fillRect(0,0,256,64);ctx.fillStyle='#d4ff00';ctx.font='bold 20px sans-serif';ctx.textAlign='center';ctx.fillText(contact.name+' · '+role,128,39);const texture=new THREE.CanvasTexture(canvas),label=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:true}));label.position.y=2.7;label.scale.set(3,.75,1);rig.group.add(label);rig.group.userData.missionContact=role;contacts.push(rig);
   }
  }
  async function request(kind){if(busy||!getId())return;const id=getId();revision++;busy=true;draw();try{const response=await fetch('/api/missions',{method:'POST',headers:{'content-type':'application/json'},signal:AbortSignal.timeout(5000),body:JSON.stringify({id,action:kind,missionId:model?.active?.id,routeId:route.value,career:mode.value==='illicit'?'illicit':'legal'})}),result=await response.json();if(!response.ok)throw Error(result.error||'Não consegui atualizar a entrega.');if(id!==getId())return;const previous=model?.active;model=result;modelAt=performance.now();if(['interact','race-checkpoint'].includes(kind)&&previous&&!model.active)toast((previous.kind==='race'?'CORRIDA CONCLUÍDA · '+(model.lastRace.time/1000).toFixed(1)+' s · ':'ENTREGA CONCLUÍDA · ')+'+'+previous.reward+' LK$');draw();}catch(e){toast(e.name==='TimeoutError'?'Conexão lenta. Confira a missão antes de tentar novamente.':e.message);}finally{busy=false;draw();}}
  function draw(){if(!model){syncContacts();description.textContent='Carregando atividades…';action.disabled=true;cancel.hidden=true;return;}if(!routesFilled){route.innerHTML='';for(const r of model.raceRoutes||[]){const o=document.createElement('option');o.value=r.id;o.textContent=r.name;route.append(o);}routesFilled=true;}const a=model.active;if(a){mode.value=a.kind==='race'?'race':a.career==='illicit'?'illicit':'delivery';if(a.kind==='race')route.value=a.routeId;}syncContacts();mode.hidden=Boolean(a);const racing=a?.kind==='race'||!a&&mode.value==='race';mode.disabled=Boolean(a)||busy;route.hidden=!racing||Boolean(a);route.disabled=Boolean(a)||busy;toggle.textContent=a?(racing?'🏁 CORRIDA':a.career==='illicit'?'📦 CLANDESTINO':'📦 ENTREGA'):'ATIVIDADES';
   if(racing){const r=(model.raceRoutes||[]).find(r=>r.id===route.value),best=Object.entries(model.bestTimes||{}).filter(([key])=>key.startsWith((a?.routeId||route.value)+':')).map(([key,t])=>key.split(':')[1]+': '+(t/1000).toFixed(1)+' s').join(' · ');description.textContent=a? a.name+' · checkpoint '+(a.checkpoint+1)+'/'+a.checkpoints.length+' · prêmio '+a.reward+' LK$':(r?.name||'Corrida')+' · vá à largada com carro ou moto. Contagem de 5 segundos, checkpoints em ordem e prêmio na chegada.'+(best?' Recordes: '+best:'');action.textContent=a?'EM CORRIDA':'LARGAR';}
   else {const illicit=mode.value==='illicit',p=model.careers?.[illicit?'illicit':'legal'],progress=p?`Nível ${p.level} · ${p.title} · ${p.completed} concluídas${p.nextAt!==null?' · próximo nível em '+Math.max(0,p.nextAt-p.completed):' · nível máximo'}. `:'';description.textContent=a?`${a.stage==='pickup'?'Pegue '+(illicit?'a cota':'o pacote')+' com '+(a.pickup.contact?.name||'o contato'):'Leve a carga até '+(a.destination.contact?.name||a.destination.label)}. Recompensa: ${a.reward} LK$ · trajeto de ${a.distance||0} m. ${progress}${illicit?'Batida frontal com viatura carregando a cota: 2 estrelas. Prisão ou morte perde a carga.':''}`:`Saldo: ${model.balance} LK$. ${progress}${illicit?'Retire a mercadoria fictícia com Zeca na favela. Paga mais; contratos mais distantes liberam nos níveis seguintes. Aceitar não gera estrelas.':'Encomendas legais, contatos sorteados por toda a cidade. Distância maior paga mais; conclua contratos para subir de nível.'}`;action.textContent=a?(a.stage==='pickup'?(illicit?'PEGAR COTA':'PEGAR PACOTE'):'ENTREGAR'):(illicit?'ACEITAR CONTRATO':'INICIAR ENTREGA');}cancel.hidden=!a;const v=getVehicle(),start=(model.raceRoutes||[]).find(r=>r.id===route.value)?.points[0];action.disabled=busy||!canUse()||Boolean(a?.kind==='race')||racing&&!a&&(!v?.driver||!['car','moto'].includes(v.kind)||!start||Math.hypot(getPosition().x-start.x,getPosition().z-start.z)>3.5);cancel.disabled=busy;}
  function target(){const a=model?.active;if(a)return a.kind==='race'?{...a.checkpoints[a.checkpoint],label:'CHECKPOINT '+(a.checkpoint+1)}:{...(a.stage==='pickup'?a.pickup:a.destination),marker:a.stage==='pickup'?'RETIRADA':'ENTREGA'};if(mode.value==='illicit')return model?.broker?{...model.broker,marker:'CONTATO'}:null;const r=mode.value==='race'&&model?.raceRoutes.find(r=>r.id===route.value);return r?{...r.points[0],label:'LARGADA · '+r.name}:null;}
  function update(time){if(time-lastFrame<100)return;lastFrame=time;const id=getId();toggle.hidden=!id;if(id!==lastId){lastId=id;revision++;model=null;syncContacts();lastPoll=-Infinity;card.hidden=true;document.body.classList.remove('mission-open');ring.visible=false;}if(!id)return;
   if(time-lastPoll>3000&&!inFlight&&!busy){lastPoll=time;inFlight=true;const pollRevision=revision;void fetch('/api/missions?id='+encodeURIComponent(id),{cache:'no-store',signal:AbortSignal.timeout(5000)}).then(async r=>{if(!r.ok)throw Error();const m=await r.json();if(id===getId()&&pollRevision===revision){model=m;modelAt=performance.now();draw();}}).catch(()=>{}).finally(()=>inFlight=false);}
   const a=model?.active,p=target(),racing=a?.kind==='race'||!a&&mode.value==='race',serverNow=model?model.serverTime+time-modelAt:Date.now();for(const rig of contacts)rig.group.visible=Boolean(id&&getPosition().distanceTo(rig.group.position)<90);ring.visible=Boolean(p&&canUse());ring.scale.setScalar(racing?3:1);if(p){const position=getPosition(),d=Math.hypot(position.x-p.x,position.z-p.z);ring.position.set(p.x,p.y+(racing?4.6:.18),p.z);const from=a?.kind==='race'?(a.checkpoint?a.checkpoints[a.checkpoint-1]:a.pickup):p;ring.rotation.set(racing?0:-Math.PI/2,racing?Math.atan2(p.x-from.x,p.z-from.z):0,0);ring.material.color.setHex(racing?0x56dfff:0xd4ff00);if(a?.kind==='race')toggle.textContent='🏁 '+(a.checkpoint+1)+'/'+a.checkpoints.length;const left=a?Math.max(0,Math.ceil((a.expiresAt-serverNow)/1000)):0;distance.textContent=racing?(a?serverNow<a.startsAt?'LARGADA EM '+Math.ceil((a.startsAt-serverNow)/1000):((serverNow-a.startsAt)/1000).toFixed(1)+' s · '+p.label:Math.ceil(d)+' m até a largada'):Math.ceil(d)+' m · '+Math.floor(left/60)+':'+String(left%60).padStart(2,'0')+' · '+p.label;const v=getVehicle();action.disabled=busy||!canUse()||Boolean(a?.kind==='race')||d>3.5||Math.abs(position.y-p.y)>2||racing&&(!v||!v.driver||!['car','moto'].includes(v.kind));if(a?.kind==='race'&&v?.driver&&d<=5.5&&serverNow>=a.startsAt&&!busy&&time-lastCheckpointRequest>750){lastCheckpointRequest=time;void request('race-checkpoint');}}else distance.textContent='LK$ é saldo de teste, sem dinheiro real.';
   if(p&&!a&&!racing)distance.textContent=Math.ceil(Math.hypot(getPosition().x-p.x,getPosition().z-p.z))+' m · '+p.label;
   if(!racing&&mode.value==='illicit')ring.material.color.setHex(0xb48aff);
  }
  toggle.addEventListener('click',()=>{card.hidden=!card.hidden;document.body.classList.toggle('mission-open',!card.hidden);draw();});card.querySelector('header button').addEventListener('click',()=>{card.hidden=true;document.body.classList.remove('mission-open');});action.addEventListener('click',()=>void request(model?.active?'interact':mode.value==='race'?'race-start':'start'));cancel.addEventListener('click',()=>void request('cancel'));card.addEventListener('pointerdown',e=>e.stopPropagation());card.addEventListener('keydown',e=>e.stopPropagation());mode.addEventListener('change',draw);route.addEventListener('change',draw);return {update,target,countingDown:()=>Boolean(model?.active?.kind==='race'&&model.serverTime+performance.now()-modelAt<model.active.startsAt)};
 }
 globalThis.LowkeyMissions={create};
})();
