(()=>{
  function install({getSelected,getCycleOrder=()=>W.order,equip,canUse,onOpen=()=>{},onClose=()=>{}}){
    const W=LowkeyWeapons,holdMs=190,root=document.createElement('div');root.id='weaponWheel';root.hidden=true;
    root.setAttribute('role','dialog');root.setAttribute('aria-label','Roda de armas');root.innerHTML='<div class="weapon-wheel-shell"><svg class="weapon-wheel-ring" viewBox="0 0 420 420" aria-hidden="true"></svg><div class="weapon-wheel-options" role="listbox" aria-label="Armas"></div><div class="weapon-wheel-center"><small>ARSENAL</small><strong></strong><span></span><b></b></div><i class="weapon-wheel-cursor"></i><div class="weapon-wheel-help">SEGURE Q · MOVA O MOUSE · SOLTE PARA EQUIPAR</div></div><div class="weapon-wheel-stats"><div>DANO <i><b></b></i></div><div>CADÊNCIA <i><b></b></i></div><div>ALCANCE <i><b></b></i></div></div>';
    const style=document.createElement('style');style.textContent=`
      #weaponWheel[hidden]{display:none!important}#weaponWheel{position:fixed;inset:0;z-index:30;display:flex;align-items:center;justify-content:center;background:radial-gradient(ellipse at center,rgba(8,16,13,.12),rgba(5,10,8,.65));touch-action:none;user-select:none;font-family:Archivo,Arial,sans-serif}
      body.weapon-wheel-open #game{filter:saturate(.35) brightness(.65)}.weapon-wheel-shell{position:relative;width:min(70vh,480px,90vw);aspect-ratio:1}.weapon-wheel-ring{position:absolute;inset:0;width:100%;height:100%;filter:drop-shadow(0 10px 24px #0008)}.weapon-wheel-ring path{fill:#cbd6ce28;stroke:#bac6be55;stroke-width:1.3;transition:fill .08s,stroke .08s}.weapon-wheel-ring path.selected{fill:#d4ff004f;stroke:#d4ff00;stroke-width:3}
      .weapon-wheel-options{position:absolute;inset:0}.weapon-wheel-option{position:absolute;width:28%;height:26%;transform:translate(-50%,-50%);border:0;background:transparent;color:#dbe4dc;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;cursor:pointer;padding:4px;font-family:inherit}.weapon-wheel-option svg{width:69%;height:57%;filter:drop-shadow(0 2px 3px #000);transition:transform .1s}.weapon-wheel-option span{font-size:10px;font-weight:900;letter-spacing:1px}.weapon-wheel-option small{font-size:10px;color:#b8c4b8}.weapon-wheel-option[aria-selected=true]{color:#d4ff00}.weapon-wheel-option[aria-selected=true] svg{transform:scale(1.1)}.weapon-wheel-option:focus-visible{outline:2px solid #d4ff00;border-radius:12px}
      .weapon-wheel-center{position:absolute;left:50%;top:50%;width:40%;height:36%;transform:translate(-50%,-50%);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;text-align:center;color:#ecf2eb;pointer-events:none}.weapon-wheel-center small{font-size:9px;letter-spacing:3px;color:#a8bca8}.weapon-wheel-center strong{font-size:clamp(18px,3vw,28px);font-weight:900;color:#d4ff00}.weapon-wheel-center span{font-size:10px;max-width:130px;line-height:1.4}.weapon-wheel-center b{font-size:11px;color:#aab8aa}.weapon-wheel-help{position:absolute;top:100%;left:50%;transform:translateX(-50%);white-space:nowrap;font-size:10px;letter-spacing:1px;font-weight:800;color:#ecf2eb;padding-top:12px}.weapon-wheel-cursor{position:absolute;left:50%;top:50%;width:7px;height:7px;border-radius:50%;background:white;box-shadow:0 0 10px #d4ff00;pointer-events:none;transform:translate(-50%,-50%)}
      .weapon-wheel-stats{position:absolute;left:calc(50% + min(35vh,240px) + 25px);top:42%;width:150px;padding:15px;border:1px solid #e2efdf22;background:#0a1512cc;border-radius:12px;color:#c4d0c2;font-size:10px;font-weight:800;letter-spacing:1px}.weapon-wheel-stats div+div{margin-top:12px}.weapon-wheel-stats i{display:block;height:5px;border-radius:3px;background:#ffffff22;margin-top:6px;overflow:hidden}.weapon-wheel-stats b{display:block;height:100%;background:#d4ff00;transition:width .12s}.weapon-icon{width:25px;height:25px;vertical-align:middle}.weapon-hud.weapon-switch{animation:weapon-switch .22s ease-out}@keyframes weapon-switch{0%{opacity:.2;transform:translate(-35%,-10px)}100%{opacity:1;transform:translate(-50%,0)}}
      @media(max-width:760px){.weapon-wheel-shell{width:min(65vh,88vw)}.weapon-wheel-stats{left:50%;top:calc(50% + min(32.5vh,44vw) + 38px);transform:translateX(-50%);width:min(320px,85vw);display:flex;gap:14px;padding:10px}.weapon-wheel-stats div{flex:1}.weapon-wheel-stats div+div{margin-top:0}.weapon-wheel-help{font-size:9px;letter-spacing:.4px}.weapon-wheel-option span{font-size:9px}.weapon-wheel-center{gap:5px}.weapon-wheel-center span{font-size:9px}.weapon-wheel-center strong{font-size:19px}@keyframes weapon-switch{0%{opacity:.2;translate:12px -5px}100%{opacity:1;translate:0 0}}}
    `;document.head.append(style);document.body.append(root);
    const ring=root.querySelector('.weapon-wheel-ring'),options=root.querySelector('.weapon-wheel-options'),center=root.querySelector('.weapon-wheel-center'),cursor=root.querySelector('.weapon-wheel-cursor'),stats=[...root.querySelectorAll('.weapon-wheel-stats b')];
    const paths=[],buttons=[],step=Math.PI*2/W.order.length,point=(r,a)=>[210+Math.sin(a)*r,210-Math.cos(a)*r];
    W.order.forEach((id,index)=>{const a=index*step-step/2+.018,b=index*step+step/2-.018,[x1,y1]=point(198,a),[x2,y2]=point(198,b),[x3,y3]=point(92,b),[x4,y4]=point(92,a),path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M${x1} ${y1} A198 198 0 0 1 ${x2} ${y2} L${x3} ${y3} A92 92 0 0 0 ${x4} ${y4} Z`);ring.append(path);paths.push(path);
      const button=document.createElement('button'),def=W.get(id);button.type='button';button.className='weapon-wheel-option';button.setAttribute('role','option');button.setAttribute('aria-label',def.name);button.style.left=`${50+Math.sin(index*step)*34.8}%`;button.style.top=`${50-Math.cos(index*step)*34.8}%`;button.innerHTML=W.icon(id)+`<span>${def.name}</span><small>${W.firearm(id)?'∞':''}</small>`;button.addEventListener('click',()=>{select(index);commit();});button.addEventListener('pointerenter',event=>{if(event.pointerType==='mouse'&&!document.pointerLockElement)select(index);});options.append(button);buttons.push(button);
    });
    let press=null,timer=null,open=false,highlight=0,vx=0,vy=0;
    function select(index){highlight=index;paths.forEach((p,i)=>p.classList.toggle('selected',i===index));buttons.forEach((b,i)=>b.setAttribute('aria-selected',String(i===index)));const def=W.get(W.order[index]);center.querySelector('strong').textContent=def.name;center.querySelector('span').textContent=def.category;center.querySelector('b').textContent=W.firearm(def.id)?'∞ MUNIÇÃO':'';stats[0].style.width=Math.min(100,def.damage*(def.pellets||1))+'%';stats[1].style.width=Math.min(100,10000/def.interval)+'%';stats[2].style.width=Math.min(100,def.range/90*100)+'%';}
    function show(){if(!press||!canUse()){cancel();return;}open=true;root.hidden=false;document.body.classList.add('weapon-wheel-open');select(Math.max(0,W.order.indexOf(getSelected())));root.querySelector('.weapon-wheel-help').textContent=press.source==='touch'?'SEGURE · ARRASTE NA DIREÇÃO DA ARMA · SOLTE':'SEGURE Q · MOVA O MOUSE · SOLTE PARA EQUIPAR';onOpen();}
    function hide(){clearTimeout(timer);timer=null;const wasOpen=open;open=false;root.hidden=true;document.body.classList.remove('weapon-wheel-open');if(wasOpen)onClose();}
    function begin(source,pointerId=null,x=0,y=0){if(press||!canUse())return false;press={source,pointerId,x,y,at:performance.now()};vx=vy=0;cursor.style.left=cursor.style.top='50%';timer=setTimeout(show,holdMs);return true;}
    function commit(){const id=W.order[highlight];hide();press=null;if(canUse())equip(id);}
    function finish(){if(!press)return;const held=performance.now()-press.at>=holdMs;if(held&&!open)show();if(open)commit();else{hide();press=null;if(canUse()){const order=getCycleOrder(),next=(order.indexOf(getSelected())+1)%order.length;equip(order[next]);}}}
    function cancel(){hide();press=null;}
    function move(x,y){const length=Math.hypot(x,y);vx=x;vy=y;if(length>180){vx=x/length*180;vy=y/length*180;}cursor.style.left=`${50+vx/420*100}%`;cursor.style.top=`${50+vy/420*100}%`;if(length>25){const angle=(Math.atan2(x,-y)+Math.PI*2)%(Math.PI*2);select(Math.round(angle/step)%W.order.length);}}
    document.addEventListener('keydown',event=>{if(event.code!=='KeyQ'||event.target.closest?.('input,textarea,[contenteditable=true]')||!canUse())return;event.preventDefault();event.stopImmediatePropagation();if(!event.repeat)begin('keyboard');},true);
    window.addEventListener('keyup',event=>{if(event.code==='KeyQ'&&press?.source==='keyboard'){event.preventDefault();event.stopImmediatePropagation();finish();}},true);
    document.addEventListener('mousemove',event=>{if(!open||press?.source!=='keyboard')return;event.preventDefault();event.stopImmediatePropagation();if(document.pointerLockElement)move(vx+event.movementX,vy+event.movementY);else{const rect=root.querySelector('.weapon-wheel-shell').getBoundingClientRect();move((event.clientX-rect.x-rect.width/2)*420/rect.width,(event.clientY-rect.y-rect.height/2)*420/rect.height);}},true);
    document.addEventListener('pointermove',event=>{if(!open||press?.source!=='touch'||event.pointerId!==press.pointerId)return;event.preventDefault();event.stopImmediatePropagation();move((event.clientX-press.x)*1.7,(event.clientY-press.y)*1.7);},{capture:true,passive:false});
    window.addEventListener('pointerup',event=>{if(press?.source==='touch'&&event.pointerId===press.pointerId){event.preventDefault();event.stopImmediatePropagation();finish();}},true);
    window.addEventListener('pointercancel',event=>{if(event.pointerId===press?.pointerId)cancel();},true);
    window.addEventListener('blur',cancel);document.addEventListener('visibilitychange',()=>{if(document.hidden)cancel();});document.addEventListener('keydown',event=>{if(event.code==='Escape'&&press){cancel();event.stopImmediatePropagation();}},true);
    select(0);
    return{begin,cancel,isOpen:()=>open,isActive:()=>Boolean(press),selected:()=>W.order[highlight],move,finish,root};
  }
  globalThis.LowkeyWeaponWheel={install};
})();
