const {chromium}=require('C:/Users/Usuário/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let model;
 // UI-only contract responses; authoritative proximity and payments have real HTTP tests.
 await page.route('http://localhost:4215/',async route=>{const response=await route.fetch();let body=(await response.text()).replace('  gameMissions=LowkeyMissions.create','  window.__careerReview={scene,avatar,id:()=>localId};\n  gameMissions=LowkeyMissions.create');body=body.replace('updatePlayerCamera(dt);','updatePlayerCamera(dt);if(window.__careerReview.focus){const p=window.__careerReview.focus;avatar.position.set(p.x,p.y,p.z);camera.position.set(p.x+5,p.y+4,p.z+7);camera.lookAt(p.x,p.y+1.4,p.z);}');await route.fulfill({response,body});});
 await page.route('**/api/state',route=>route.fulfill({status:204}));
 await page.route('**/api/missions*',async route=>{if(!model){const response=await route.fetch();model=await response.json();}const data=route.request().method()==='POST'?route.request().postDataJSON():null;if(data?.action==='start')model.active={id:'ui-fixture',kind:'delivery',career:data.career,level:1,stage:'pickup',pickup:model.broker,destination:{...model.broker,x:model.broker.x+40,label:'Entrega',contact:{...model.broker.contact,name:'Dudu'}},reward:300,distance:40,expiresAt:Date.now()+600000};if(data?.action==='cancel')model.active=null;model.serverTime=Date.now();await route.fulfill({json:model});});
 await context.request.post('http://localhost:4215/api/auth/register',{data:{username:'careers_'+Date.now().toString(36),password:'Synthetic-test-123'}});await page.goto('http://localhost:4215/');await page.locator('#startButton').click();await page.waitForFunction(()=>window.__careerReview?.id());await page.evaluate(()=>document.exitPointerLock?.());await page.locator('.mission-toggle').click();await page.getByLabel('Tipo de atividade').selectOption('illicit');await page.waitForFunction(()=>window.__careerReview.scene.children.filter(g=>g.userData.missionContact).length===1);
 assert.match(await page.locator('.mission-card p').innerText(),/Novato/);await page.evaluate(p=>window.__careerReview.focus=p,model.broker);await page.getByRole('button',{name:'ACEITAR CONTRATO',exact:true}).click();await page.waitForFunction(()=>window.__careerReview.scene.children.filter(g=>g.userData.missionContact).length===2);assert.match(await page.locator('.mission-card p').innerText(),/cota/);
 for(const size of [{width:390,height:844},{width:844,height:390},{width:320,height:568}]){await page.setViewportSize(size);await page.waitForTimeout(150);assert.equal(await page.locator('.mission-card').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}),true,'card fits the viewport and scrolls');await page.getByRole('button',{name:'CANCELAR',exact:true}).scrollIntoViewIfNeeded();}
 await page.waitForTimeout(3300);assert.equal(await page.evaluate(()=>window.__careerReview.scene.children.filter(g=>g.userData.missionContact).length),2,'polls do not duplicate the two contacts');await page.screenshot({path:__dirname+'/careers-mobile.png'});await page.getByRole('button',{name:'CANCELAR',exact:true}).click();await page.waitForFunction(()=>window.__careerReview.scene.children.filter(g=>g.userData.missionContact).length===1);await page.getByLabel('Tipo de atividade').selectOption('delivery');await page.waitForFunction(()=>window.__careerReview.scene.children.filter(g=>g.userData.missionContact).length===0);assert.deepEqual(errors,[]);console.log('PASS: legal/illicit careers, broker, bounded contacts, cancellation and portrait/landscape UI');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
