const {chromium}=require('C:/Users/Usuário/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const context=await browser.newContext({viewport:{width:1280,height:800}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log(e.message);});
 await page.goto('http://localhost:4215/?preview=islands',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('nav[aria-label="Prévia das ilhas"]'));await page.waitForTimeout(1200);await page.screenshot({path:__dirname+'/islands-aerial.png'});
 assert.equal(await page.evaluate(()=>LowkeyCityLayout.islands.length),3);assert.equal(await page.locator('#accountScreen').isVisible(),false);assert.equal(await page.getByRole('link',{name:'PONTES',exact:true}).count(),1);
 for(const size of [{width:390,height:844},{width:844,height:390},{width:320,height:568}]){await page.setViewportSize(size);await page.waitForTimeout(200);assert.equal(await page.locator('nav[aria-label="Prévia das ilhas"]').evaluate(nav=>[...nav.querySelectorAll('a')].every(a=>{const r=a.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;})),true,'preview navigation fits portrait and landscape');}await page.setViewportSize({width:1280,height:800});
 const districts=await page.evaluate(()=>({airports:LowkeyCityLayout.airports.length,districts:LowkeyCityLayout.districts.length}));assert.deepEqual(districts,{airports:2,districts:4});
 for(const view of (process.env.LOWKEY_DETAIL_VIEWS?.split(',')||['airport-west','airport-main','festival','downtown','favela','rural','mansions','heliport','statue'])){await page.goto('http://localhost:4215/?preview='+view+'&lighting=day',{waitUntil:'domcontentloaded'});await page.locator('#accountScreen').waitFor({state:'hidden'});await page.waitForTimeout(500);await page.screenshot({path:__dirname+'/district-'+view+'.png'});console.log('Preview checked: '+view);}
 await page.goto('http://localhost:4215/?preview=islands',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('nav[aria-label="Prévia das ilhas"]'));
 await page.getByRole('link',{name:'PONTES',exact:true}).click();await page.waitForTimeout(1000);await page.screenshot({path:__dirname+'/islands-bridge.png'});
 await page.getByRole('link',{name:'EXPLORAR · CONTA TESTE',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#accountScreen').classList.contains('hidden'));await page.locator('#startButton').click();await page.evaluate(()=>document.exitPointerLock?.());await page.waitForTimeout(800);
 await page.getByRole('button',{name:'Abrir mapa',exact:true}).click();await page.screenshot({path:__dirname+'/islands-map.png'});assert.equal(await page.locator('.lk-map').isVisible(),true);
 assert.deepEqual(errors,[]);console.log('PASS: islands, bridges, map and local test account load without browser errors');await context.close();
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
