const assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Usuário/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  try{for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:800},hasTouch:mobile,isMobile:mobile}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
    const registration=await context.request.post('http://localhost:4212/api/auth/register',{data:{username:'map_'+Date.now().toString(36),password:'Synthetic-map-test-123'}});assert.equal(registration.status(),201);await page.goto('http://localhost:4212/');await page.locator('#startButton').click();await page.evaluate(()=>document.exitPointerLock?.());await page.locator('.lk-map-toggle').waitFor({state:'visible'});
    if(mobile)await page.locator('.lk-map-toggle').tap();else await page.keyboard.press('m');await page.locator('.lk-map').waitFor({state:'visible'});assert.match(await page.locator('.lk-map footer').textContent(),/SEM PERSEGUIÇÃO/);
    assert.equal(await page.locator('.lk-map').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}),true,'map fits viewport');
    const markers=await page.evaluate(()=>{const rig={state:{id:'test-cop',health:100},group:{position:{x:10,z:20}}},police={stars:()=>0,rigs:new Map([['test',rig]])};const none=LowkeyMap.policeMarkers(police,'me');police.stars=()=>2;const active=LowkeyMap.policeMarkers(police,'me');rig.state.health=0;return{none,active,dead:LowkeyMap.policeMarkers(police,'me')};});assert.deepEqual(markers.none,[]);assert.deepEqual(markers.active,[{id:'test-cop',x:10,z:20}]);assert.deepEqual(markers.dead,[]);
    await page.screenshot({path:mobile?'preview-map-mobile.png':'preview-map-pc.png'});await page.getByRole('button',{name:'Fechar mapa',exact:true}).click();await page.locator('.lk-map').waitFor({state:'hidden'});assert.deepEqual(errors,[]);console.log(JSON.stringify({mobile,mapFits:true,markers:true,errors}));await context.close();
  }}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
