const {chromium}=require('C:/Users/Usuário/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const view of (process.env.LOWKEY_METROPOLIS_VIEWS?.split(',')||['islands','bridges','prison','city','beach'])){await page.goto('http://localhost:4215/?preview='+view+'&lighting='+(view==='city'?'night':'day'),{waitUntil:'domcontentloaded'});await page.locator('#accountScreen').waitFor({state:'hidden'});await page.waitForTimeout(800);await page.screenshot({path:__dirname+'/metropolis-'+view+'.png'});assert.equal(await page.evaluate(()=>LowkeyCityLayout.islands.length),4);console.log('Checked '+view);}
await page.goto('http://localhost:4215/?preview=explore');await page.locator('#accountScreen').waitFor({state:'hidden'});await page.locator('#startButton').click();await page.evaluate(()=>document.exitPointerLock?.());
// Inject only a simulated arrest event, exercising the real responsive prison UI.
await page.evaluate(()=>{const controller=LowkeyPolice.create({THREE,scene:new THREE.Scene(),makeAvatar(){},disposeAvatar(){},getLocalId:()=> 'ui-fixture',getPosition:()=>LowkeyCityLayout.jail,onArrest(){},onRelease(){}});controller.receive({type:'police-arrest',serverTime:Date.now(),until:Date.now()+120000,position:LowkeyCityLayout.jail});controller.update(.016,performance.now());});
for(const size of [{width:390,height:844},{width:844,height:390},{width:320,height:568}]){await page.setViewportSize(size);await page.waitForTimeout(200);const bounds=await page.getByRole('button',{name:'Trabalhar · descontar 15s'}).evaluate(b=>{const r=b.getBoundingClientRect();return {visible:r.width>0,fits:r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight};});assert.deepEqual(bounds,{visible:true,fits:true});}
assert.deepEqual(errors,[]);console.log('PASS: map previews and prison UI without browser errors');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
