const {chromium}=require('C:/Users/Usuário/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 for(const [width,height]of [[390,844],[844,390],[320,568],[667,375]]){
  const context=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('http://localhost:4214/',async route=>{const response=await route.fetch();const body=(await response.text()).replace('  gameMissions=LowkeyMissions.create','  window.__mobileReview={id:()=>localId,axes:touchAxes,arm(){avatar.position.set(0,0,80);localInSafeZone=false;equipWeapon(\'glock\',false,false);weaponSwitchUntil=0;},aiming:()=>glockAiming,debug:()=>({selectedWeapon,weaponSwitchPending,weaponSwitchUntil,now:performance.now(),position:avatar.position.toArray(),connected,localHealth,localVehicleId,localGhost,localHijackPending,held:[...heldAttackPointers]})};\n  gameMissions=LowkeyMissions.create');await route.fulfill({response,body});});
  await page.route('**/api/state',route=>route.fulfill({status:204}));let shots=0;await page.route('**/api/combat',route=>{if(route.request().postDataJSON().action==='glock')shots++;return route.fulfill({status:200,json:{}})});
  await page.route('**/mobile-ui.css*',route=>route.fulfill({contentType:'text/css',body:require('node:fs').readFileSync(__dirname+'/../mobile-ui.css','utf8')}));
  await context.request.post('http://localhost:4214/api/auth/register',{data:{username:'ui_'+Date.now().toString(36),password:'Synthetic-test-123'}});
  await page.goto('http://localhost:4214/');await page.locator('#startButton').click();await page.waitForFunction(()=>window.__mobileReview?.id());await page.locator('.mission-toggle').waitFor({state:'visible'});
  await page.locator('.lk-phone-toggle').waitFor({state:'visible'});
  const selectors=['#moveStick','#touchJump','#touchEmotes','#mobileChatToggle','#voiceToggle','.lk-phone-toggle','.lk-map-toggle','.mission-toggle','[data-combat="aim"]','[data-combat="attack"]'];
  const boxes=await page.evaluate(selectors=>selectors.map(s=>({s,...document.querySelector(s).getBoundingClientRect().toJSON()})),selectors);
  for(const b of boxes){assert.ok(b.width>=44&&b.height>=44,b.s+' is touch sized');assert.ok(b.x>=0&&b.y>=0&&b.right<=width&&b.bottom<=height,b.s+' is inside screen');}
  for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert.ok(Math.min(a.right,b.right)<=Math.max(a.x,b.x)||Math.min(a.bottom,b.bottom)<=Math.max(a.y,b.y),a.s+' overlaps '+b.s);}
  await page.evaluate(()=>window.__mobileReview.arm());await page.waitForTimeout(300);
  const center=s=>{const b=boxes.find(b=>b.s===s);return{x:b.x+b.width/2,y:b.y+b.height/2}},move=center('#moveStick'),aim=center('[data-combat="aim"]'),attack=center('[data-combat="attack"]'),cdp=await context.newCDPSession(page),finger=(id,p)=>({id,x:p.x,y:p.y,radiusX:2,radiusY:2,force:1});
  const moving={...move,y:move.y-25};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[finger(1,move)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[finger(1,moving)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[finger(1,moving),finger(2,aim)]});await page.waitForTimeout(300);assert.ok(await page.evaluate(()=>window.__mobileReview.aiming()));
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[finger(1,moving),finger(2,aim),finger(3,attack)]});for(let n=0;!shots&&n<30;n++)await page.waitForTimeout(100);if(!shots)console.log('TOUCH DEBUG',await page.evaluate(()=>window.__mobileReview.debug()));assert.ok(shots>0,'fires while moving and holding aim');assert.ok(Math.abs(await page.evaluate(()=>window.__mobileReview.axes.moveY))>.2);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.__mobileReview.aiming()),false);assert.equal(await page.evaluate(()=>window.__mobileReview.axes.moveY),0);
  await page.locator('.mission-toggle').click();await page.getByRole('button',{name:'INICIAR ENTREGA',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.mission-card p').textContent.includes('Pegue o pacote'));await page.screenshot({path:__dirname+`/mission-${width}.png`});await page.getByRole('button',{name:'Fechar missões'}).click();
  console.log(JSON.stringify({width,height,errors,rects:await page.evaluate(()=>Object.fromEntries(['#moveStick','#touchJump','#touchEmotes','#mobileChatToggle','#voiceToggle','.lk-phone-toggle','.lk-map-toggle','.combat-bar','.weapon-hud'].map(s=>{const e=document.querySelector(s);return[s,e?.getBoundingClientRect().toJSON()]})))}));assert.deepEqual(errors,[]);
  await page.screenshot({path:__dirname+`/mobile-${width}.png`});
  await page.locator('#editorToggle').click();await page.waitForTimeout(300);await page.screenshot({path:__dirname+`/editor-${width}.png`});
  console.log('EDITOR',await page.evaluate(()=>({classes:document.body.className,combat:getComputedStyle(document.querySelector('.combat-bar')).display,map:getComputedStyle(document.querySelector('.lk-map-toggle')).display})));assert.equal(await page.locator('.lk-map-toggle').isVisible(),false);assert.equal(await page.locator('.combat-bar').isVisible(),false);
  await page.setViewportSize({width:height,height:width});await page.waitForFunction(expected=>document.body.classList.contains('mobile-avatar-preview')===expected,height<width);
  await page.locator('#closeEditor').click();assert.equal(await page.evaluate(()=>document.body.classList.contains('avatar-editing')),false);assert.equal(await page.evaluate(()=>document.body.classList.contains('mobile-avatar-preview')),false);assert.deepEqual(errors,[]);
  await context.close();
 }
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
